### ISSUE TITLE
Is https://registry.opendata.aws/terrain-tiles/  not a supported format?

### ISSUE THREAD

**Issue by johnjore** [fabric-io-rodrigues/GeoTiffCOG#8]
I was hoping to use this library in my little project and using https://registry.opendata.aws/terrain-tiles/ as the elevation source as its freely available.

using `aws s3 cp --no-sign-request s3://elevation-tiles-prod/geotiff/10/926/626.tif c:\626.tif` to download a file (I might have downloaded the wrong tif file, but not too fussed at this point)

```
GeoTiff COG - version: 0.1
--------------------------
Unhandled Exception: System.Exception: Error in ParseGeoDataAtPoint: Index was outside the bounds of the array.
   at GeoTiffCOG.GeoTiff.GetElevationAtPoint(Int32 x, Int32 y) in C:\Data\\GeoTiffCOG\GeoTiff.cs:line 202
   at GeoTiffCOG.GeoTiff.GetElevationAtLatLon(Double latitude, Double longitude) in C:\Data\GeoTiffCOG\GeoTiff.cs:line 150
   at GeoTiffCOGConsole.Program.Main(String[] args) in C:\Data\GeoTiffCOGConsole\Program.cs:line 32
```

Hardcoded the GPS location I am looking for, and modified the URL to use a local file:
```
//double lat = Convert.ToDouble(args[1]);
//double lon = Convert.ToDouble(args[2]);
double lat = -37.4075974;
double lon = 145.7524722;

//GeoTiff geoTiff = new GeoTiff(new Uri(url), directoryTemp);
GeoTiff geoTiff = new GeoTiff(url);
```

When using "SLV_wind-speed_50m.tif" as the input file, the elevation comes back as zero without crashing. Assuming zero is the default when the location is not within the tif file.

Does not look like GeoTiffCOG is happy with the format of the tif file from the S3 bucket?

**Comment by fabric-io-rodrigues** [comment]
Hi @johnjore, thanks for posting your issue.

I added a small correction to support the integer raster type (INT) there was a code that applied the value 0 (if there was no factor), so it would always be returned zero.

Also, to obtain the height value using this raster (which is projected in meters) it will be necessary to inform the lat/lon (y,x) in meters.

In your example:
```csharp
double lat = -37.4075974;
double lon = 145.7524722;
// change to:
double lat = -4496073.92;
double lon = 16225090.99;
```
Can see more in: https://epsg.io/transform#s_srs=4326&t_srs=3857&x=145.7524722&y=-37.4075975

And you can also use the URL directly in the function (without having to download it from S3), see the example below:
```csharp
string url_s3 = "https://elevation-tiles-prod.s3.amazonaws.com/geotiff/10/926/626.tif";
GeoTiff geoTiff = new GeoTiff(new Uri(url_s3), directoryTemp);
double value = geoTiff.GetElevationAtLatLon(lat, lon);
```

Please confirm if this information is useful and solve the problem, so that we can close it.

**Comment by johnjore** [comment]
Looking good, does not crash when the coordinates are within the boundaries of the TIF file and it spits out a number that looks accurate. Thanks for the quick turn around!
